### ISSUE TITLE
Etiquette note

### ISSUE THREAD

**Issue by RichJackson** [CogStack/CogStack-Pipeline#1]
Hello Cogstack (Amos right?). Just a quick etiquette poke - sorry! Provenance wise, it's bad form to start a new repo without acknowledging existing github projects. It's better to fork (e.g. [here](https://github.com/RichJackson/cogstack) or [here](https://github.com/KHP-Informatics/cogstack)   

:)

**Comment by afolarin** [comment]
@RichJackson happy to acknowledge, we are tidying up KHPinformatics (and the original CogStack should have gone into this). Happy to cite work and papers however if you'd like.
