### ISSUE TITLE
Test LSTM OCR Engine in Tesseract

### ISSUE THREAD

**Issue by afolarin** [CogStack/CogStack-Pipeline#30]
Need to setup some basic benchmarks to test this. Keen to know if it helps with rotations.

https://github.com/tesseract-ocr/tesseract/wiki/4.0-with-LSTM
https://github.com/tesseract-ocr/tesseract/issues/40
https://github.com/tesseract-ocr/tesseract/issues/465

**Comment by jstuczyn** [comment]
I've just updated the Tesseract version on our dev environment to 4.0.0alpha and rerun the problematic test (the one with document with rather bad quality, where the tables are not aligned, etc) and the result is significantly better than on the older version. 
For comparison:
Actual text:
```
(2) If only one person is ticket *(part of letter "d' is not visible and in fact it looks like a "t")* in the final two columns then they are the nearest relatives.
```
3.04.01:
```
{2} Heel}; 0ch persnn is tieket in the final twrr eeltrnms their Hwy are the nearest relatives.
```

4.0.0alpha:
```
(2) If only one person is ticket in the final twn columns then they are the nearest relatives,
```

However, that does not mean 4.0.0 only makes tiny mistakes like two -> twn, but there are significantly less of them and it is possible to understand the meaning of a sentence regardless of them.

**Comment by afolarin** [comment]
Yeah, I was keen to see how much better the LSTM OCR engine is. Given that it's still in alpha, but sounds like it is both more accurate and faster

**Comment by afolarin** [comment]
TODO set as default configuration

**Comment by lrog** [comment]
The precision and recall of the new tesseract has been significantly improved according to the official [tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/4.0-Accuracy-and-Performance ). On few our tests we could also notice significant improvements running locally on MTSamples.

The openjdk v.11 base image (based on Debian) already provides in the repository the new version of tesseract. Hence, with PR #65 we added the new version of tesseract to be used by default within the upcoming version of CogStack Pipeline image. The same for TravisCI builds.

I'm closing this issue, however, creating a proper benchmark suite to gather precision/recall/performance metrics would be a good idea to have a direct metrics for future improvements.
