### ISSUE TITLE
ElasticsearchRest Client will fail silently if index contains invalid character

### ISSUE THREAD

**Issue by jstuczyn** [CogStack/CogStack-Pipeline#32]
If `elasticsearch.index.name` contains an invalid character (in my case I had a trailing space), it will silently fail. Cogstack will not catch an error. I can only suspect that performRequest() does not throw IOException. 
Every log will say that document were successfully written.

This, however, will raise an issue with the native Java Client.

**Comment by afolarin** [comment]
cc @HeglerTissot perhaps this is related to the logging issue you observed on your test corpus of 1k docs

**Comment by HeglerTissot** [comment]
The issue I found is about multiple and consecutive runs of the same job, when the partitioning timestamp field does not contains a full millisecond mask in the source database. In this case, when documents share the same timestamp in different partitions, only those in the first partition will be loaded. To avoid that, use the following mask (with "ffff") for the timestamp partitioning field:

format(<timestamp_field>,'yyyy-MM-dd HH:mm:ss.ffff')

* This practice does NOT necessarily fix the issue but will avoid it happening amap - probably will NOT happen in a view that is being constantly updated with new records.
