### ISSUE TITLE
Cogstack docker download issues

### ISSUE THREAD

**Issue by polyglot-v** [CogStack/CogStack-Pipeline#38]
I am not able to pull the bioyodie when I run the .yml file:

bioyodie:
    cpu_quota: 800000
    image: richjackson/bioyodie:D4.5
    ports:
      - 8080:8080
Neither can I pull cogstack:

cogstack:
    image: richjackson/cogstack:1.2.0

When I search bioyodie on docker hub, I find nothing.
For cogstack, docker hub shows cogstack/cogstack but we get an error message at runtime that we need to provide docker login/password for cogstack.

**Comment by afolarin** [comment]
We are in the process of migrating all the containers to cogstacksystems/cogstack.

For BioYodie I think there may be some licencing issue (I'm just checking).

**Comment by afolarin** [comment]
@polyglot-v original bioyodie pipeline was not opensourced at the original time, it has since been released https://github.com/GateNLP/Bio-YODIE.

**Comment by afolarin** [comment]
cc/ @angusroberts are there remaining issues releasing the working BIOYODIE pipeline
cc/ @Honghan pls comment on MetaMap alternative

**Comment by afolarin** [comment]
The issue here is around releasing the UMLS resources which are under licence, the BioYODIE application is under AGPL. We therefore can't release a docker container image with it.

UMLS licence required for ontology resource files
 - for research purposes: https://uts.nlm.nih.gov/license.html.
 
BioYODIE
 - https://gate.ac.uk/applications/bio-yodie.html (docs)
 - https://github.com/GateNLP/Bio-YODIE (repo)

**Comment by yatharthranjan** [comment]
I think maybe the PR #44 should provide a workaround to this this as well since its built during docker-compose up

**Comment by lrog** [comment]
Regarding obtaining and running the BioYodie, we unfortunately cannot provide the BioYodie image bundled with the UMLS resources. 
FYI, we are also slowly moving away from using NLP applications inside CogStack Pipeline where the newest approach, running a multi-step processing pipeline, has been covered in the [official documentation](https://cogstack.atlassian.net/wiki/spaces/COGDOC/pages/573440014/Full+ingestion+pipeline+recipe) with the available source code under: https://github.com/CogStack/CogStack-Recipes
Alternatively, one can run BioYodie as a part of [SemEHR](https://github.com/CogStack/CogStack-SemEHR/).
