### ISSUE TITLE
OCR Test failure

### ISSUE THREAD

**Issue by jstuczyn** [CogStack/CogStack-Pipeline#4]
This might be consequence of resolving issue #3 as the build would not finish successfully, because it would fail at test stage. The assertion `assertTrue(parsedString.contains("Father or mother"))` in `testParseRequiringOCR` inside `PDFPreprocessorParserTest.java` fails. Rather than being recognised as "Father or mother", the OCR'd document contains the string "Father **er** mother".

**Comment by jstuczyn** [comment]
I've compared the outputs produced by:
```
tesseract 3.03 
with leptonica-1.70
```
and
```
tesseract 3.04.01
with leptonica-1.73
```
And for some reason the output of the first one (the older version) seems to be of better quality, with less misspelled words and less wrongly recognised characters. It might be due to some non-obvious configuration of tesseract in the first case that changed with the fresh installation of newer version.

**Comment by afolarin** [comment]
I suspect this is a result of #3 
@jstuczyn I think in anycase cogstack#30 is likely to close this?

**Comment by lrog** [comment]
Using the new version of Tesseract 4.0 solves this issue -- the text is recognised correctly.
The new version of tesseract is already in `dev` branch via PR #65 .
Therefore, this test has been once again re-enabled in `dev` in commit 2c3bdd0c91a1fe3cb66fcec1b492f418e262ddfd.
