### ISSUE TITLE
Refactor the build process

### ISSUE THREAD

**Issue by afolarin** [CogStack/CogStack-Pipeline#40]
CogStack-Pipeline/build.gradle 
seems to doing a lot of extraneous things like building containers. 

- [x] cleanup container building code
- [x] Use docker-compose to build the containers
- [x] odd scripts
- [x] config file generation
- [x] Move old scripts to deprecated and will be deleted in the future builds
- [x] Add initial travis build
- [x] Configure Travis for CI. Will require admin access to github repo

**Comment by yatharthranjan** [comment]
closed by #44
