### ISSUE TITLE
Can we add more than one elastic search hosts in the config ?

### ISSUE THREAD

**Issue by yatharthranjan** [CogStack/CogStack-Pipeline#46]
Can we add more than one host for elastic search in the configuration here-  https://github.com/CogStack/CogStack-Pipeline/blob/8767232468cbcceda5c41cf62d22f4cd892b7622/docker-cogstack/cogstack/cogstack_conf/example.properties#L5  ?

If this is not posiible right now, it should be implemented. This is required since we have moved towards a multi-host deployment of elasticsearch. @Honghan @HeglerTissot ?

**Comment by afolarin** [comment]
If I understand correctly then perhaps we should provide an array available elasticsearch nodes names/IP, but will prob have to refactor

value seems to get populated into clusterHost 
https://github.com/CogStack/CogStack-Pipeline/blob/8f1e2f3d837806b70c5fd5334595d524b129e04c/src/main/java/uk/ac/kcl/service/ESRestService.java#L65

https://github.com/CogStack/CogStack-Pipeline/blob/8f1e2f3d837806b70c5fd5334595d524b129e04c/src/main/java/uk/ac/kcl/service/ESRestService.java#L116-L132

and

https://github.com/CogStack/CogStack-Pipeline/blob/2ba5605635cb9d8fbd3e87c25acbfff5c283ede2/src/main/java/uk/ac/kcl/itemWriters/ElasticsearchDocumentWriter.java#L70

https://github.com/CogStack/CogStack-Pipeline/blob/2ba5605635cb9d8fbd3e87c25acbfff5c283ede2/src/main/java/uk/ac/kcl/itemWriters/ElasticsearchDocumentWriter.java#L118-L130

**Comment by yatharthranjan** [comment]
Yes agreed. The RestClient.builder can take multiple hosts as arguments https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.0/java-rest-low-usage-initialization.html

**Comment by afolarin** [comment]
Good spot -- ok I think init with an array of available master nodes probably makes a lot of sense. ~~Assuming that the  RestClient round robin over those specified hosts rather than just clobber one node~~.
edit:
it does:
https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-client/6.0.1/index.html
> allows to send a request to the cluster. When sending a request, a host gets selected out of the provided ones in a round-robin fashion.

**Comment by lrog** [comment]
Added in PR #64
