### ISSUE TITLE
TesseractOCRParser timeouts on longer documents

### ISSUE THREAD

**Issue by jstuczyn** [CogStack/CogStack-Pipeline#5]
For some longer documents (having more than 10 pages, especially if they are scanned), OCR is going to fail (and hence PDF and thumbnail generation) as Tesseract parsing will timeout before it manages to finish. It is because it is using the default timeout of 120s.

It would have been beneficial if it was possible to set this value using the config file.

**Comment by afolarin** [comment]
Is this timeout not part of the config? If not it should be :+1:

**Comment by lrog** [comment]
This feature has been implemented in `feat-tika-timeout` branch -- commit: 64a96a3fce0c7741408a4f30128179178554657a .

Two properties have been provided, implemented in TikaDocumentItemProcessor.java :
- `tika.tesseract.timeout` -- max. timeout [in seconds] for Tesseract for running OCR before it fails.
- `tika.convert.timeout` -- max. timeout [in seconds] for ImageMagick for documents conversion (PDF --> TIFF; a part of PDF preprocessing) before it fails.

When not specified, the default values are used -- in both cases: 120 s.
