### ISSUE TITLE
Towards modularity in CogStack for site-specific features

### ISSUE THREAD

**Issue by afolarin** [CogStack/CogStack-Pipeline#7]
_From @hkkenneth on March 25, 2017 13:58_

As CogStack is being deployed at various NHS sites and projects, some site-specific features will be needed. For example, in an UCL project we need to post-process bio-yodie results. In the SLaM timeline project we need to generate thumbnails and PDFs. Both of these are not needed in other CogStack use case.

Goal: new features can be implemented in separate project, loaded dynamically as extra JAR files and configured using properties and profiles.

_Copied from original issue: KHP-Informatics/cogstack#17_

**Comment by afolarin** [comment]
see example for Signum project https://github.com/KHP-Informatics/cogstack-plugin-signum

**Comment by RichJackson** [comment]
I dunno. Seems like scope creep to me. Why not just hand off site specific requirements to microservices? E.g. https://github.com/RichJackson/cogstack/blob/master/src/main/java/uk/ac/kcl/itemProcessors/WebserviceDocumentItemProcessor.java

**Comment by afolarin** [comment]
In anycase would be useful to reuse (especially for any common scenario/EHR type) specific functional extensions regardless of how they are packaged. 

Will put this feature on hold for now till it is understood how best to implement.
