### ISSUE TITLE
Unable to view links on confluence

### ISSUE THREAD

**Issue by torrybr** [CogStack/CogStack-Pipeline#83]
Im unable to access the job property specific links on the confluence

On [this](https://cogstack.atlassian.net/wiki/spaces/COGDOC/pages/16678946/CogStack+Pipeline) page, specifically [this](https://cogstack.atlassian.net/wiki/pages/resumedraft.action?draftId=16678946#CogStackPipeline-processors) link

Thanks!

**Comment by vladd-bit** [comment]
The first link works, however, I suggest taking a look at https://github.com/CogStack/CogStack-NiFi, this repositoy is no longer kept up to date and it will not be maintained any longer.
